export const hints = [
  "Related to or concerning something.",
  "A user profile or financial record.",
  "From one side to the other.",
  "The process of adding something.",
  "The time following an event.",
  "One more time; repeatedly.",
  "In opposition to.",
  "A mutual arrangement or understanding.",
  "Very nearly; not quite.",
  "In the midst of something.",
  "Quantity or total of something.",
  "Something that entertains or amuses.",
  "A shape formed by two lines from a common point.",
  "Feeling of displeasure or annoyance.",
  "A living creature that is not human.",
  "A response to a question.",
  "A technical machine or device.",
  "A common round fruit, usually red or green.",
  "Acceptance or agreement with something.",
  "A disagreement or heated exchange.",
  "To take aggressive action against.",
  "To make an effort or try.",
  "Notice taken of someone or something.",
  "Power or right to give orders.",
  "Works by itself with little to no help.",
  "Not asleep; conscious.",
  "A state of equilibrium or stability.",
  "A wide round container used for liquids.",
  "An open container used for carrying items.",
  "Pleasing to look at.",
  "For the reason that.",
  "Earlier than a point in time.",
  "Way someone acts or conducts themselves.",
  "Trust or confidence in something.",
  "A small, juicy fruit.",
  "In the space separating two things.",
  "The beginning of life.",
  "Having a strong or unpleasant taste.",
  "The darkest color.",
  "A sharp-edged cutting tool.",
  "Red liquid in the body.",
  "Flat, thin, rectangular object.",
  "The act of boiling or being boiled.",
  "A container with a narrow neck.",
  "Organ inside your head that controls the body.",
  "A device to stop motion.",
  "A part of a tree that grows out from the trunk.",
  "A yellowish metal made from copper and zinc.",
  "Baked food made from flour.",
  "Air taken into and expelled from the lungs.",
  "A small block used for building.",
  "A structure built to cross over something.",
  "Giving off lots of light or intelligent.",
  "Damaged or not working properly.",
  "Male sibling.",
  "Color between red and yellow.",
  "Tool used for painting or cleaning.",
  "Open container for carrying liquid or sand.",
  "A structure with a roof and walls.",
  "To break suddenly and violently.",
  "The practice of making or doing work.",
  "A dairy product used in cooking or spread on bread.",
  "Small disc or switch that you press.",
  "Device used to take pictures.",
  "A strong cloth for painting or sailing.",
  "Wheeled transport pulled by horses.",
  "A reason or justification.",
  "Known for sure; confident.",
  "A series of connected links.",
  "Soft white rock used for drawing.",
  "An opportunity or probability.",
  "To make or become different.",
  "Low in price or cost.",
  "A dairy product made from milk.",
  "A substance used in or made by chemistry.",
  "Front part of the body between neck and stomach.",
  "Leader or ruler of a group.",
  "A place for Christian worship.",
  "A round shape with all points equidistant from center.",
  "Free from dirt or mess.",
  "Easy to understand or see.",
  "Device for telling time.",
  "Material for making clothes.",
  "White or gray mass in the sky.",
  "Part of a shirt around the neck.",
  "Visual property resulting from light reflection.",
  "A state of physical ease and freedom.",
  "A group organized for a specific function.",
  "Ordinary; shared by all.",
  "An organized group working together.",
  "Having all necessary parts.",
  "Not simple; made of many parts.",
  "State of health or something being required.",
  "Aware and responsive to surroundings.",
  "To have power over something.",
  "A reddish-brown metal.",
  "Soft, white fluffy fabric.",
  "Sudden expulsion of air from lungs.",
  "A nation or land.",
  "Something that protects or hides.",
  "A break or split.",
  "Recognition for payment or trust.",
  "An illegal act.",
  "Lacking kindness; harsh.",
  "To press or squeeze forcefully.",
  "Happening now or a flow of electricity.",
  "A piece of fabric used to cover a window.",
  "A smoothly bending line.",
  "A soft pillow or padding.",
  "Harm or injury.",
  "The possibility of harm.",
  "A female child of parents.",
  "The end of life.",
  "A choice or conclusion reached.",
  "A unit for measuring temperature or angle.",
  "Easily broken or damaged.",
  "Needing someone or something else.",
  "A plan or drawing to show how something will look.",
  "A strong feeling of wanting.",
  "A small part of something.",
  "Not the same as another.",
  "The process of breaking down food.",
  "The path along which something moves.",
  "Not clean.",
  "Finding something for the first time.",
  "A condition that harms the body.",
  "A strong feeling of dislike or nausea.",
  "The space between two things.",
  "The action of separating something.",
  "A feeling of uncertainty.",
  "To remove water or liquid.",
  "A sliding compartment in furniture.",
  "Clothing worn by women or girls.",
  "A liquid you swallow.",
  "Operating a vehicle.",
  "Happening before the expected time.",
  "The planet we live on.",
  "The process of teaching and learning.",
  "A result or outcome of an action.",
  "Able to stretch and return to shape.",
  "Using or relating to electricity.",
  "A machine that converts energy to motion.",
  "Sufficient in quantity.",
  "Being the same in quantity, size, or value.",
  "A mistake.",
  "Something that happens.",
  "Each individual one.",
  "Something used to show how others are like.",
  "Giving one thing for another.",
  "The state of being real.",
  "The act of becoming larger.",
  "A person highly skilled in a subject.",
  "Not true or incorrect.",
  "People related by blood or marriage.",
  "A male parent.",
  "A part of a bird used for flying.",
  "Lacking physical strength.",
  "An emotional state or reaction.",
  "Relating to the sex that can bear offspring.",
  "Able to produce abundantly.",
  "Something imaginary or not real.",
  "An open area of land.",
  "A physical struggle or battle.",
  "A part of the hand.",
  "Coming before all others.",
  "Firmly in place; not movable.",
  "A burning gas or fire.",
  "The act of flying.",
  "The lower surface of a room.",
  "The colored part of a plant.",
  "Lacking good sense.",
  "Physical power or strength.",
  "In the direction ahead.",
  "A rigid structure giving shape.",
  "Happening often.",
  "Someone you like and trust.",
  "The part that faces forward.",
  "A sweet or edible part of a plant.",
  "Time yet to come.",
  "A place where plants are grown.",
  "Common or widespread.",
  "A hard, transparent substance.",
  "A covering for the hand.",
  "Small hard particles from plants or food.",
  "Plants with thin green leaves.",
  "Very large in size or extent.",
  "The color between blue and yellow.",
  "A number of people or things together.",
  "The process of increasing in size.",
  "A person who shows the way.",
  "A tool used for pounding.",
  "Suspended from above.",
  "Feeling joy or contentment.",
  "A place where ships dock.",
  "Peaceful or agreeable arrangement.",
  "In good physical condition.",
  "The ability to hear.",
  "The organ that pumps blood.",
  "The study of past events.",
  "Having a space inside; not solid.",
  "A large animal used for riding or work.",
  "A place for medical treatment.",
  "A building for people to live in.",
  "The quality of being funny or amusing.",
  "Having great meaning or value.",
  "A sudden urge or drive.",
  "To become greater in size or amount.",
  "Economic activity related to making goods.",
  "A small bug or creature with six legs.",
  "Protection against future loss.",
  "A feeling of curiosity or concern.",
  "A newly created device or idea.",
  "A piece of land surrounded by water.",
  "A soft, sweet substance like jelly.",
  "A precious stone or gem.",
  "Travel from one place to another.",
  "A person who decides legal matters.",
  "A container for boiling water.",
  "A cutting tool with a sharp blade.",
  "Facts, information, and skills acquired.",
  "A system of communication by speech or writing.",
  "A sound showing amusement or joy.",
  "The act of gaining knowledge or skill.",
  "Material made from animal skin.",
  "A written or printed message.",
  "A flat, horizontal surface.",
  "A place to borrow books.",
  "Something that makes things visible.",
  "A boundary or maximum.",
  "A fabric made from flax.",
  "A substance that flows freely.",
  "Small in size or amount.",
  "Being alive.",
  "Not tight or secure.",
  "A device with moving parts to do work.",
  "A person in charge of tasks or people.",
  "A place where goods are bought and sold.",
  "Having a husband or wife.",
  "A contest or comparison.",
  "The substance something is made of.",
  "To find the size, amount, or degree.",
  "Relating to health or medicine.",
  "A gathering of people.",
  "The ability to remember.",
  "A hard, shiny substance like iron or gold.",
  "The point that is equally distant from sides.",
  "Relating to the armed forces.",
  "A unit of time equal to 60 seconds.",
  "Made by combining different things.",
  "A medium of exchange, like coins or bills.",
  "A primate with a long tail.",
  "One of the twelve parts of a year.",
  "The early part of the day.",
  "A female parent.",
  "Movement from one place to another.",
  "A large natural elevation of the earth.",
  "The part of the face used for eating and talking.",
  "Tissue in the body that produces movement.",
  "Organized sound that is pleasing to hear.",
  "Not wide; limited in width.",
  "A large group of people under one government.",
  "Exists in or produced by nature.",
  "Required or essential.",
  "A small, thin tool used for sewing.",
  "A bundle of fibers in the body or mind.",
  "The time of day when it's dark.",
  "A sound, especially one that's loud or unpleasant.",
  "Usual or expected.",
  "One of the four cardinal directions.",
  "A mathematical value that shows quantity.",
  "To present something for acceptance.",
  "A place where work or business is done.",
  "A surgical procedure or organized action.",
  "What someone thinks or believes.",
  "Completely different in nature or direction.",
  "A round citrus fruit.",
  "An instruction or sequence.",
  "A decorative object.",
  "Referring to something else.",
  "Someone who possesses something.",
  "Colored liquid used to create art.",
  "Material for writing or printing on.",
  "Two lines side by side, always the same distance apart.",
  "A wrapped package.",
  "A soft substance used to stick things.",
  "Money given for something.",
  "Freedom from conflict or disturbance.",
  "An instrument for writing or drawing.",
  "A human being.",
  "Relating to the body.",
  "A visual representation of something.",
  "A specific location.",
  "A flying vehicle with wings.",
  "A living organism that grows in soil.",
  "A flat dish used for food.",
  "To make someone happy or satisfied.",
  "A feeling of enjoyment or delight.",
  "A tool used in farming to turn soil.",
  "A small pouch for carrying things.",
  "An exact location or detail.",
  "A substance that can cause harm or death.",
  "To make something shiny or clean.",
  "Relating to government or public affairs.",
  "A person employed to carry luggage.",
  "A particular place or arrangement.",
  "Able to be done or achieved.",
  "A starchy vegetable that grows underground.",
  "A fine, dry substance.",
  "The ability to do work or cause change.",
  "To give or show something.",
  "The cost of something.",
  "To make text or images on paper.",
  "A place where criminals are kept.",
  "Not shared with others.",
  "Likely to happen.",
  "A series of actions to achieve a result.",
  "To make or create something.",
  "A financial gain.",
  "Things owned by someone.",
  "Written or spoken language that is not poetry.",
  "An expression of objection.",
  "Open to everyone.",
  "The reason something is done.",
  "The standard of something.",
  "Something asked to be answered.",
  "Happening very fast.",
  "Making very little noise.",
  "Completely or entirely.",
  "The area covered between limits.",
  "A response to an action.",
  "The act of looking at and understanding words.",
  "Prepared for action or use.",
  "A cause or explanation for something.",
  "A written confirmation of money received.",
  "A written or stored account of events.",
  "A feeling of sadness about something done.",
  "Happening at expected times.",
  "A connection between people or things.",
  "Belief in a god or gods.",
  "To ask for something politely.",
  "Admiration for someone or something.",
  "Something given for a good deed.",
  "A regular pattern of sound or movement.",
  "Morally correct or a direction.",
  "A natural stream of water.",
  "Having an uneven surface.",
  "Shaped like a circle.",
  "A system of marks used for measurement.",
  "A place for learning.",
  "The study of the natural world.",
  "A cutting tool with two blades.",
  "A tool with a spiral ridge.",
  "One-sixtieth of a minute or coming after first.",
  "Something kept hidden from others.",
  "A person who handles office tasks.",
  "The act of choosing from a group.",
  "A physical feeling or meaning.",
  "To divide or set apart.",
  "Being very important or grave.",
  "A person employed to work for others.",
  "Darkness caused by blocking light.",
  "To move something quickly up and down.",
  "A feeling of embarrassment or guilt.",
  "Having a fine point or edge.",
  "A woolly farm animal.",
  "A flat surface for storage.",
  "A piece of clothing for the upper body.",
  "A sudden upsetting surprise.",
  "Not long in length or time.",
  "A shiny white metal.",
  "Easy to understand or not complicated.",
  "A female sibling.",
  "A piece of clothing worn from the waist down.",
  "To rest with eyes closed.",
  "A surface that is not level.",
  "Not large in size or amount.",
  "To break something with force.",
  "A scent detected by the nose.",
  "An expression of happiness on the face.",
  "Visible gas from something burning.",
  "Having a flat, even surface.",
  "A long, legless reptile.",
  "A sudden, involuntary burst of air from the nose.",
  "A community of people living together.",
  "Firm and not hollow or liquid.",
  "A noise or audio vibration.",
  "One of the four cardinal directions.",
  "The empty area around things.",
  "A tool used for digging.",
  "Different from the usual; unique.",
  "A soft, absorbent material.",
  "A utensil used for eating or stirring.",
  "A season or a coil of wire.",
  "A shape with four equal sides.",
  "A part of a performance or process.",
  "A small piece of paper to show payment.",
  "To begin or initiate.",
  "Something that is said or declared.",
  "A place where public services operate.",
  "Hot vapor from boiling water.",
  "A hard, strong metal.",
  "A thin piece of wood or material.",
  "Tending to adhere or cling.",
  "Not easily bent or moved.",
  "Not moving; calm or quiet.",
  "A loop of thread used in sewing.",
  "A close-fitting garment for the legs.",
  "An internal organ for digestion.",
  "A hard solid mineral material.",
  "A place where items are kept for sale.",
  "A tale or account of events.",
  "Without curve or bend.",
  "Unusual or unfamiliar.",
  "A public road in a city or town.",
  "To extend or pull something.",
  "Having great physical power.",
  "Something that is built or formed.",
  "A type of material or matter.",
  "Happening quickly and unexpectedly.",
  "A sweet substance from plants.",
  "The warmest season of the year.",
  "To provide help or assistance.",
  "An unexpected event or reaction.",
  "Having a pleasant taste.",
  "A set of connected things or parts.",
  "A piece of furniture with a flat top.",
  "The sense that lets you detect flavors.",
  "The act or profession of educating.",
  "An inclination or habit.",
  "An idea or explanation.",
  "In or at that place.",
  "Not thin; having depth.",
  "An object or item.",
  "A mental process or idea.",
  "A thin strand of fiber.",
  "The front part of the neck.",
  "Moving in one side and out the other.",
  "Moving from one side to another.",
  "The short, thick finger.",
  "A loud rumbling sound during storms.",
  "A slip showing admission or travel.",
  "Fastened firmly; not loose.",
  "In need of rest or sleep.",
  "With each other.",
  "The day after today.",
  "A part of the mouth used for taste.",
  "A hard structure inside the mouth.",
  "To make contact by hand or object.",
  "The act of buying and selling.",
  "A series of connected vehicles.",
  "The act of moving something.",
  "A cunning act or prank.",
  "Difficulty or distress.",
  "Clothing worn from the waist down.",
  "To bend into a spiral shape.",
  "Used to protect from rain.",
  "In a lower position.",
  "The worth of something.",
  "A line of poetry.",
  "A container for liquids.",
  "Using or involving force.",
  "The sound made when speaking.",
  "The act of delaying or staying.",
  "Unwanted or useless material.",
  "To look at or observe.",
  "A clear liquid essential for life.",
  "Conditions like rain, sun, etc.",
  "How heavy something is.",
  "A circular object that turns.",
  "At what place or location.",
  "During the time that.",
  "A high-pitched blowing sound.",
  "The lightest color; opposite of black.",
  "An opening in a wall for light.",
  "The coldest season of the year.",
  "An adult female human.",
  "An injury to the body.",
  "The act of forming letters or text.",
  "Not correct or mistaken.",
  "A bright color like a lemon.",
  "The day before today.",
  "Not old; having little age.",
]
